#############################################################################
# Makefile for building: OpptimizerN9
# Generated by qmake (2.01a) (Qt 4.7.4) on: Thu Apr 19 01:04:55 2012
# Project:  OpptimizerN9.pro
# Template: subdirs
# Command: i:/qtsdk/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe -spec ../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile OpptimizerN9.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = i:/qtsdk/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-OptUI \
		sub-OptDaemon

OptUI/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) OptUI/ || $(MKDIR) OptUI/ 
	cd OptUI/ && $(QMAKE) i:/Qt/OpptimizerN9/OptUI/OptUI.pro -spec ../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o $(MAKEFILE)
sub-OptUI-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) OptUI/ || $(MKDIR) OptUI/ 
	cd OptUI/ && $(QMAKE) i:/Qt/OpptimizerN9/OptUI/OptUI.pro -spec ../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o $(MAKEFILE)
sub-OptUI: OptUI/$(MAKEFILE) FORCE
	cd OptUI/ && $(MAKE) -f $(MAKEFILE)
sub-OptUI-make_default: OptUI/$(MAKEFILE) FORCE
	cd OptUI/ && $(MAKE) -f $(MAKEFILE) 
sub-OptUI-make_first: OptUI/$(MAKEFILE) FORCE
	cd OptUI/ && $(MAKE) -f $(MAKEFILE) first
sub-OptUI-all: OptUI/$(MAKEFILE) FORCE
	cd OptUI/ && $(MAKE) -f $(MAKEFILE) all
sub-OptUI-clean: OptUI/$(MAKEFILE) FORCE
	cd OptUI/ && $(MAKE) -f $(MAKEFILE) clean
sub-OptUI-distclean: OptUI/$(MAKEFILE) FORCE
	cd OptUI/ && $(MAKE) -f $(MAKEFILE) distclean
sub-OptUI-install_subtargets: OptUI/$(MAKEFILE) FORCE
	cd OptUI/ && $(MAKE) -f $(MAKEFILE) install
sub-OptUI-uninstall_subtargets: OptUI/$(MAKEFILE) FORCE
	cd OptUI/ && $(MAKE) -f $(MAKEFILE) uninstall
OptDaemon/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) OptDaemon/ || $(MKDIR) OptDaemon/ 
	cd OptDaemon/ && $(QMAKE) i:/Qt/OpptimizerN9/OptDaemon/OptDaemon.pro -spec ../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o $(MAKEFILE)
sub-OptDaemon-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) OptDaemon/ || $(MKDIR) OptDaemon/ 
	cd OptDaemon/ && $(QMAKE) i:/Qt/OpptimizerN9/OptDaemon/OptDaemon.pro -spec ../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o $(MAKEFILE)
sub-OptDaemon: OptDaemon/$(MAKEFILE) FORCE
	cd OptDaemon/ && $(MAKE) -f $(MAKEFILE)
sub-OptDaemon-make_default: OptDaemon/$(MAKEFILE) FORCE
	cd OptDaemon/ && $(MAKE) -f $(MAKEFILE) 
sub-OptDaemon-make_first: OptDaemon/$(MAKEFILE) FORCE
	cd OptDaemon/ && $(MAKE) -f $(MAKEFILE) first
sub-OptDaemon-all: OptDaemon/$(MAKEFILE) FORCE
	cd OptDaemon/ && $(MAKE) -f $(MAKEFILE) all
sub-OptDaemon-clean: OptDaemon/$(MAKEFILE) FORCE
	cd OptDaemon/ && $(MAKE) -f $(MAKEFILE) clean
sub-OptDaemon-distclean: OptDaemon/$(MAKEFILE) FORCE
	cd OptDaemon/ && $(MAKE) -f $(MAKEFILE) distclean
sub-OptDaemon-install_subtargets: OptDaemon/$(MAKEFILE) FORCE
	cd OptDaemon/ && $(MAKE) -f $(MAKEFILE) install
sub-OptDaemon-uninstall_subtargets: OptDaemon/$(MAKEFILE) FORCE
	cd OptDaemon/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: OpptimizerN9.pro  ../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default/qmake.conf ../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf
	$(QMAKE) -spec ../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile OpptimizerN9.pro
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile OpptimizerN9.pro

qmake_all: sub-OptUI-qmake_all sub-OptDaemon-qmake_all FORCE

make_default: sub-OptUI-make_default sub-OptDaemon-make_default FORCE
make_first: sub-OptUI-make_first sub-OptDaemon-make_first FORCE
all: sub-OptUI-all sub-OptDaemon-all FORCE
clean: sub-OptUI-clean sub-OptDaemon-clean FORCE
distclean: sub-OptUI-distclean sub-OptDaemon-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-OptUI-install_subtargets sub-OptDaemon-install_subtargets FORCE
uninstall_subtargets: sub-OptUI-uninstall_subtargets sub-OptDaemon-uninstall_subtargets FORCE

sub-OptUI-check: OptUI/$(MAKEFILE)
	cd OptUI/ && $(MAKE) check
sub-OptDaemon-check: OptDaemon/$(MAKEFILE)
	cd OptDaemon/ && $(MAKE) check
check: sub-OptUI-check sub-OptDaemon-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install_target2: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/etc/init/apps/ || $(MKDIR) $(INSTALL_ROOT)/etc/init/apps/ 
	-$(INSTALL_FILE) i:/Qt/OpptimizerN9/qtc_packaging/debian_harmattan/opptimizer-daemon.conf $(INSTALL_ROOT)/etc/init/apps/


uninstall_target2:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/etc/init/apps/opptimizer-daemon.conf
	-$(DEL_DIR) $(INSTALL_ROOT)/etc/init/apps/ 


install_target3: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/lib/modules/2.6.32.48-dfl61-20115101/ || $(MKDIR) $(INSTALL_ROOT)/lib/modules/2.6.32.48-dfl61-20115101/ 
	-$(INSTALL_FILE) i:/Qt/OpptimizerN9/qtc_packaging/debian_harmattan/symsearch.ko $(INSTALL_ROOT)/lib/modules/2.6.32.48-dfl61-20115101/
	-$(INSTALL_FILE) i:/Qt/OpptimizerN9/qtc_packaging/debian_harmattan/opptimizer_n9.ko $(INSTALL_ROOT)/lib/modules/2.6.32.48-dfl61-20115101/


uninstall_target3:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/lib/modules/2.6.32.48-dfl61-20115101/symsearch.ko 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/lib/modules/2.6.32.48-dfl61-20115101/opptimizer_n9.ko
	-$(DEL_DIR) $(INSTALL_ROOT)/lib/modules/2.6.32.48-dfl61-20115101/ 


install: install_subtargets install_target2 install_target3  FORCE

uninstall: uninstall_target2 uninstall_target3  uninstall_subtargets FORCE

FORCE:

